name: health_worker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  appwrite: ^11.0.0
  bitsdojo_window: any
  camera: ^0.10.5+5
  camera_windows: ^0.2.1+8
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.3
  envied: ^0.3.0+3
  floor: ^1.4.2
  fluent_ui: ^4.7.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  getwidget: ^4.0.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  path_provider: ^2.1.1
  styled_widget: ^0.4.1
  system_theme: ^2.3.1
  uuid: ^4.1.0
  window_manager: ^0.3.7

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.4

dependency_overrides:
  win32: 5.0.9

  bitsdojo_window:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window.git
      path: bitsdojo_window

  bitsdojo_window_platform_interface:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window.git
      path: bitsdojo_window_platform_interface

  bitsdojo_window_windows:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window.git
      path: bitsdojo_window_windows

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

msix_config:
  display_name: Health Worker
  publisher_display_name: laurencetroyv
  identity_name: otoscopia.health.worker
  msix_version: 1.0.0.0
  logo_path: C:\path\to\logo.png
  capabilities: internetClient, location, picturesLibrary, webcam, videosLibrary,
    lowLevelDevices
