name: otoscopia_health_worker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  appwrite: ^11.0.0
  cupertino_icons: ^1.0.2
  envied: ^0.3.0+3
  fluent_ui: ^4.7.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  ionicons: ^0.2.2
  system_theme: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.4

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
