name: health_worker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  appwrite: ^11.0.0
  camera: ^0.10.5+5
  camera_windows: ^0.2.1+8
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.8
  encrypt: ^5.0.3
  envied: ^0.5.1
  fluent_ui: ^4.7.7
  flutter:
    sdk: flutter
  flutter_offline: ^3.0.0
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  ionicons: ^0.2.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  pdf: ^3.10.4
  printing: ^5.11.0
  responsive_framework: ^1.1.1
  responsive_grid_list: ^1.4.0
  sentry_flutter: ^7.12.0
  styled_widget: ^0.4.1
  system_theme: ^2.3.1
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
